# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ v.1.5.x ]
  pull_request:
    branches: [ v.1.5.x ]

jobs:
  build:

    runs-on: [macos-latest, ubuntu-latest, ubuntu-latest]

    steps:
      - name: Setup / Checkout
        uses: actions/checkout@v2
      - name: Setup / Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
      - name: Setup / JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Setup / settings.xml
        uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: '[{"id": "default", "username": "${{ secrets.nexus_user }}", "password": "${{ secrets.nexus_password }}"}]'
          mirrors: '[{"id": "default", "name": "default", "mirrorOf": "*", "url": "https://nexus.adito.cloud/repository/maven-public/"}]'
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Maven / Download Dependencies
        run: mvn -Dmaven.artifact.threads=30 -T 1C -B de.qaware.maven:go-offline-maven-plugin:1.2.8:resolve-dependencies
      - name: Native / Compile
        run: mvn clean package -Pnative -Dquarkus.container-image.build=true
      - name: Native / Integration Test
        run: mvn -Pnative test-compile failsafe:integration-test failsafe:verify
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
